### ISSUE TITLE
Website not accessible

### ISSUE THREAD

**Issue by alisongomeiz** [borenstein-lab/burrito#12]
Hi there:

I am very interested in using BURRITO for some metagenomics analysis I've been working on after reading up on the documentation. However, the website linked on GitHub and your website is down. Is there a new link available or something wrong with the website? 

Thank you.

**Comment by engal** [comment]
I think it should be back up, can you check again?

**Comment by alisongomeiz** [comment]
Yes it's back up, thank you!

**Comment by engal** [comment]
Great, I'll close this out.
