### ISSUE TITLE
How to generate custom genomic content and functional attribution

### ISSUE THREAD

**Issue by amoltej** [borenstein-lab/burrito#17]
Hi, I am new to Burrito and using 16s analysis based on SILVA-132 database. I prepared other input files using
 `qiime picrust2` 
command where I got all the associated KO numbers and their count based on OTU table and provided taxanomy.
But this process does not give me files related to custom genomic content/functional attribution. 
Hence when I upload my data (without custom genomic content/functional attribution) i get following error message 
`The selected function abundance table was in an invalid table format. Please select a file in a valid table format`

I can not see any guidelines to get this data either on picrust/qiime/burrito manual. 
Could you please help me to resolve the issue?

Thanks in advance

**Comment by engal** [comment]
Hi,

You can find details on generating a functional attribution table using PICRUSt2 in the "Generate metagenome predictions" section of the PICRUSt2 tutorial [here](https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.4.1)#generate-metagenome-predictions). This contains instructions on generated a stratified PICRUSt2 output file, and if you scroll down to the bottom of that subsection, you'll find instructions on how to generate a legacy PICRUSt1 version of this output table, which can be used with BURRITO.

Hope that helps!

**Comment by amoltej** [comment]
Thanks for quick response.
It worked and now I have got all the necessary files required to run burrito. 

but now after uploading files i get message "following OUT are present in contribution file but not in OTU file" what does this mean? which file it is referring as contribution file?

**Comment by engal** [comment]
The contribution file is the stratified PICRUSt2 table. This message suggests that there are OTUs/ASVs present in the stratified PICRUSt2 table that are not present in your taxonomic abundance table. BURRITO requires that any taxon with functional contributions also be present in the taxonomic abundance table.

If you find that all of the taxa in your contribution table are present in your taxonomic abundance table, then there may be a formatting issue with in the input files. If this is the case, sending the first 5 lines or so of each input file should help me figure out what's going on.

**Comment by amoltej** [comment]
I compared the OTU numbers between file but they are all present in all files
here is the sample data as you mentioned. 

[https://drive.google.com/drive/folders/1E9WzAg9P48lhcCP2nJOJsDqp45auOLt0?usp=sharing](url)

Thanks for all the help
Cheers

**Comment by engal** [comment]
Could you try removing the "-" characters in your column names in the sample_grouping.txt file (e.g. change "sample-id" to "sample" and "body-site" to "bodysite")? Those characters cause issues when in column names. Once you've made those changes, could you try your data again and let me know what happens?

**Comment by amoltej** [comment]
Hi, thanks, I performed analysis by removing the "-". and double checked for number of OTUs but it was still showing same result. 
After careful observation I realized that the OTU that was flagged as missing had no read counts for any sample. 
I removed those OTU's from all the files and burrito analysis completed successfully. 
But after completion I do not see any graphs on the screen (screenshot below) 
i can only download "burrito_function_abundances.tab-1.omcsettings" and "burrito_contributions.tab.omcsettings" files. 

how can I get it working?


![image](https://user-images.githubusercontent.com/17108522/114966955-ed747180-9eb6-11eb-90dd-ea746abde37e.png)

**Comment by engal** [comment]
Hmm, I may need you to share the full data files for me to figure out what's going on here. My first guess is that for some reason BURRITO is filtering out all of the OTU and/or function abundances, which leaves empty plots. However, I'll probably need more information to understand the issue. Is it possible for you to upload your data files to the drive folder you shared with me?

**Comment by amoltej** [comment]
Here are all the files I used for analysis
Thanks

https://1drv.ms/u/s!AnutfSj9fsoTqStBy-ZkDKwpEQhl?e=szcK9C

**Comment by engal** [comment]
Wanted to give you a quick update, based on my testing so far it looks like the issue arises when using your metagenome abundance table. If you don't upload that, then BURRITO can use everything else correctly.

I'm still looking into why the metagenome abundance table is causing problems, but while I'm working on that you can start visualizing the rest of your data if you want.

**Comment by engal** [comment]
Sorry for the delay. It looks like there's another formatting issue, though this one is a bit more annoying to fix. Currently, if you want to use a metagenome abundance table for comparison with your stratified table, your sample names cannot include the "." character. In my testing, I replaced "." with "_" in all of your sample names and that worked.

**Comment by amoltej** [comment]
Thanks yes, it does not like "." in column names and also it does not like to change the sequence of the columns in attribution file.

Once again thanks for your time and assistance
