### ISSUE TITLE
application unexpectedly exited

### ISSUE THREAD

**Issue by Sofie8** [borenstein-lab/burrito#2]
Hi,

Can you help me out with the following error :
![image](https://user-images.githubusercontent.com/29913361/39670074-d442b024-50ca-11e8-84a4-d4eb06727f77.png)
My OTU table is attached, picked closed ref against Greengenes 13_5.

[otuburrito.txt](https://github.com/borenstein-lab/burrito/files/1977354/otuburrito.txt)

Thanks,
Sofie

**Comment by engal** [comment]
Hi Sofie,

Sorry to hear you're having issues with BURRITO. Hopefully we can help you get everything working.

I just tried running BURRITO with the OTU table you sent, and everything seemed to work, so it doesn't seem to be an issue with your OTU table.

Did you change any of the default options on the upload page? If so, could you tell me what you changed so I can try to replicate the bug?

Best,
Alex

**Comment by Sofie8** [comment]
Hi Alex,

Yes, I figgered it out today, it was my design table and formatting that
broke it.
Now it indeed runs ok!

Thanks for the great tool.
I have also Piphyllin predicted output, but since it does not pick against
full genomes, I guess taxonomic inference will not be possible?

Cheers,
Sofie



2018-05-08 16:46 GMT-04:00 engal <notifications@github.com>:

**Comment by engal** [comment]
If you can get a genomic content table for your OTUs that links OTUs to the functions used in the Piphyllin output, or a table directly linking your OTUs to their contributions in the Piphyllin output, then you should be able to visualize that.
