### ISSUE TITLE
Data visualisation produce black line

### ISSUE THREAD

**Issue by FelixGiraud** [borenstein-lab/burrito#22]
Hello and thank you for developping Burrito, 
I'm really excited to try out Burrito on my data ! However when i'm upload my data this is what i see: 
![image](https://user-images.githubusercontent.com/47348139/122943828-a358b200-d377-11eb-8e47-3f6af870573c.png)

This is what looks like 10 first line of my taxonomic abundance table: 
![image](https://user-images.githubusercontent.com/47348139/122944078-d0a56000-d377-11eb-8c5b-4913ecdaf4a0.png)
Metagenome function abundance: 
![image](https://user-images.githubusercontent.com/47348139/122944221-eb77d480-d377-11eb-8399-b546cdf07102.png)

Do you see any issue in my data ? or uploading with Greengenes and KO IDs is the reason why this does not work ? 
Thank you.

**Comment by engal** [comment]
Can you try renaming your samples so that there are no period characters (".") in the sample names? I think that may be related to your issue.

**Comment by FelixGiraud** [comment]
Thank you ! 
It totally fixed my issue.
