### ISSUE TITLE
The following OTU_IDs are in the OTU table but are not present in the PICRUSt 16S normalization table

### ISSUE THREAD

**Issue by FelixGiraud** [borenstein-lab/burrito#23]
Hello, 
I'm really enjoying Burrito and have managed to run it with one dataset.
However, i've been trying to upload a second dataset many times already without success. 

Here is my OTU table:
[otu_well_formated.txt](https://github.com/borenstein-lab/burrito/files/6829378/otu_well_formated.txt)
My metadata table:
[metadata_well_formated.txt](https://github.com/borenstein-lab/burrito/files/6829384/metadata_well_formated.txt)
And my metagenome predictions:
[pred_burrito_ok.txt](https://github.com/borenstein-lab/burrito/files/6829389/pred_burrito_ok.txt)

I'm really confused since I tried to switch the GG ID's of this dataset with the IDs of my first dataset and Burrito worked just fine. 
If you have any idea I would really appreciate. 
Thank you.

**Comment by engal** [comment]
Hi,

How did you pick these OTUs? Looking at the gg_13_5_otus reference set (see [here](https://greengenes.secondgenome.com/?prefix=downloads/greengenes_database/gg_13_5/)), the OTUs in your table do not appear to have associated representative sequences.

**Comment by FelixGiraud** [comment]
I used this command in order to generate my table: 

qiime2 vsearch cluster-features-closed-reference \
  --i-table table.qza \ --> table genrated with Dada2
  --i-sequences rep-seqs.qza \ --> input sequences
  --i-reference-sequences 99_otus.qza \ --> GG_13_5 sequences.
  --p-perc-identity 0.99 \
  --o-clustered-table table-cr-99.qza \
  --o-clustered-sequences rep-seqs-cr-99.qza \
  --o-unmatched-sequences unmatched-cr-99.qza

Then I converted the file to a tab delimited format.
I can definitly find matches between the gg_13_5_taxonomy and the gg_13_5 fasta using the link you provided.

I'm really confused, I'm probably missing something but I can't figure out what it is...

**Comment by engal** [comment]
Where did you get your 99_otus.qza file from? The IDs may exist in the taxonomy file, but there is no associated representative sequence the Greengenes 99_otus.fasta file that contains the representative sequences for 99% identity clustering (which is found in the gg_13_5_otus archive on the page I linked).

**Comment by FelixGiraud** [comment]
Looks like this is it. I used the gg_13_5.fasta.gz instead of the gg_13_5_otus.gz file. I'll give it a try and close the subject if the problem is solved. Thank you very much for your help.

**Comment by FelixGiraud** [comment]
Works perfectly. Thank you 👍

**Comment by stepnap** [comment]
Hii, this is my first time using BURRITO. But when I try to use the tools I have this error: 
The following OTU_IDs are in the OTU table but are not present in the PICRUSt 16S normalization table: ....
Here my OTU table, taxonomy and metadata. 
[taxonomy2.txt](https://github.com/borenstein-lab/burrito/files/10033455/taxonomy2.txt)
[OTU.txt](https://github.com/borenstein-lab/burrito/files/10033469/OTU.txt)
[metadata.txt](https://github.com/borenstein-lab/burrito/files/10033470/metadata.txt)
If you have any idea I would really appreciate.
Thank you :).

**Comment by stepnap** [comment]
Is possible that burrito work well only with OTU and not with AVS ?
