### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by ADGM** [borenstein-lab/burrito#3]
Hi!

I would like to ask if the website is working properly, because I can't seem to successfully upload datasets? I even tried downloading the sample datasets provided and get the same result: the selected file will appear in the upload box, then disappear after a few seconds. I tried with different browsers and in Ubuntu and Windows 10 and I get the same result.

![screenshot1](https://user-images.githubusercontent.com/10193506/58192638-82699280-7cc1-11e9-8e3e-ccefb5b814be.png)
![screenshot2](https://user-images.githubusercontent.com/10193506/58192640-85648300-7cc1-11e9-9601-a431715ff212.png)

Hope I can be helped with this. Thank you!

**Comment by engal** [comment]
Hi!

Glad to hear you're interested in using BURRITO. This may be related to a recent visual bug that we haven't had the chance to address yet. Your files may actually have been successfully uploaded, but for some reason the displayed text is being reset to "No file selected".

Can you upload all of your files, ignore the fact that it says "No file selected", try running BURRITO, and let us know what happens?

Best,
Alex

**Comment by ADGM** [comment]
That worked for me: it executed anyway even if the uploaded file doesn't show in the box. 
But now I get a different error relating to my not uploading a function abundance table. May I ask if this is a requisite for the tool to work?

![image](https://user-images.githubusercontent.com/10193506/58193653-c362a680-7cc3-11e9-9d22-492fd0142052.png)

**Comment by engal** [comment]
Does your OTU table use Greengenes OTU IDs?

By default, BURRITO uses data from PICRUSt 1.0 to determine the links between taxonomic and function abundances. Specifically, the default data we have available links Greengenes OTU IDs to KO copy numbers. This means that Greengenes OTU IDs are required if you want to run BURRITO without either a genomic content table for the taxa in your taxonomic abundance table or an explicit attribution table and function abundance table. Without Greengenes OTU IDs, you'll need to use one of those alternative options.

**Comment by cnoecker** [comment]
Hi - to add onto what Alex said above, if you are uploading a table of ASVs from Qiime2 (as it appears), you can run the latest version of PICRUSt2 on your table with the `--metagenome_contrib` flag and it will produce an attribution table in the format required for BURRITO. Alternatively, you can use vsearch (or the qiime2-vsearch plugin) to map your ASVs to Greengenes OTUs, and BURRITO would be able to infer functions for that.

**Comment by ADGM** [comment]
Hi, sorry this issue has been drawn out. My taxonomy table was generated using SILVA (and, yes, from Qiime2) and since I plan to stick with my SILVA taxonomic classification I opted to do the suggestion of producing the PICRUSt2 metegenome_contrib table. However, the output format of that appears to still be incompatible; it returns this message when I try to upload it:

![Screenshot from 2019-05-23 17-27-26](https://user-images.githubusercontent.com/10193506/58265822-b8ba1700-7d80-11e9-9455-b6a882854e65.png)

The PICRUSt function attribution file has only 6 columns: from Sample to CountContributedbyOTU.

In the meantime I will try using a Greengenes-annotated taxonomy table instead and hopefully that would work.

**Comment by cnoecker** [comment]
Hi, thanks for your patience. It turns out that there was a bug in the column-checking function that caused it to reject your table even though it has the correct number of columns. You should be able to use your SILVA attribution table now.
