### ISSUE TITLE
Service unavailable

### ISSUE THREAD

**Issue by dlivin** [borenstein-lab/burrito#30]
Hello,

I am trying to use the software, but there is a service unavailable error, is the server in maintenance downtime, or having capacity problems? 

Thanks,
Dawson

**Comment by elhanan-borenstein** [comment]
Should be working now. 

 

From: Elhanan Borenstein ***@***.*** 
Sent: Monday, 6 June 2022 21:47
To: 'borenstein-lab/burrito' ***@***.***>
Subject: RE: [borenstein-lab/burrito] Service unavailable (Issue #30)

 

Thanks Dawson – we are aware of the problem and will hopefully resolve in the next couple of days. Best wishes, Elhanan

 

 

From: dlivin ***@***.*** 
Sent: Thursday, 2 June 2022 16:34
To: borenstein-lab/burrito ***@***.*** ***@***.***> >
Cc: Subscribed ***@***.*** ***@***.***> >
Subject: [borenstein-lab/burrito] Service unavailable (Issue #30)

 

Hello,

I am trying to use the software, but there is a service unavailable error, is the server in maintenance downtime, or having capacity problems?

Thanks,
Dawson

**Comment by elhanan-borenstein** [comment]
Thanks Dawson – we are aware of the problem and will hopefully resolve in the next couple of days. Best wishes, Elhanan

 

 

From: dlivin ***@***.*** 
Sent: Thursday, 2 June 2022 16:34
To: borenstein-lab/burrito ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [borenstein-lab/burrito] Service unavailable (Issue #30)

 

Hello,

I am trying to use the software, but there is a service unavailable error, is the server in maintenance downtime, or having capacity problems?

Thanks,
Dawson
