### ISSUE TITLE
OTUs absent from contribution table

### ISSUE THREAD

**Issue by Qepanna** [borenstein-lab/burrito#8]
Hi!

I previously had an issue concerning data size and I managed to succesfully use BURRITO with a small sample of my data.

This time, I tried reducing my data set just enought for BURRITO to work, but I get this error instead:
![image](https://user-images.githubusercontent.com/66706307/84717489-f23d6180-af43-11ea-8dd5-5147632838ed.png)

Since I used the same code as I did before, I don't understand where this error comes from...

Thank you for your help!

**Comment by engal** [comment]
Sorry, that's a bug in our code. We had been assuming that any taxa present in the taxonomic profile would have some contribution to the community functional profile, but it's possible that might not be the case for certain functional annotation systems or if you have filtered your data down to look at a specific set of functions.

I've updated that check to give a warning (still informing the user which taxa are absent from the contribution table), but BURRITO will now continue as normal from that point.

Please try your data again and let me know if there are any other issues.

**Comment by Qepanna** [comment]
Thank you for your quick respond!

I forgot to mention that when I clicked OK it returned to the main page...

Anyway, I tried it again and this time I got a new message right after the previous one:
![image](https://user-images.githubusercontent.com/66706307/84815828-9a553800-afe1-11ea-8219-7665b07edce9.png)

I clicked OK, it went to Step5 real fast and imediately crashed: I got disconnected from the server and I had no choice but to go back to the main page.

**Comment by engal** [comment]
Would you be able to share the data you used that caused the crash? If it's crashing without an error message, then it would be best for me to replicate the issue myself and see what's happening.

**Comment by Qepanna** [comment]
The files I used are there:

https://drive.google.com/drive/folders/1y7aLZbRzr1z4gGlpnlusGDkzVM85bOAn?usp=sharing

**Comment by engal** [comment]
Quick update: I was able to run that data successfully through BURRITO when I left out the metadata file, so you might be able to try it that way. I'm still working on what's going wrong when the metadata file is present.

**Comment by engal** [comment]
Ok, I've fixed a plotting bug that could occur when a taxon had no associated contributions and changed the warning messages (messages that the user should be alerted to, but should not stop data processing) to print to the browser console, which should decrease the chance of disconnecting from the server. You may need to clear your browser cache and reload the web page to see these changes.

I've also identified an issue with your metadata file. Specifically, the column name "sample-id". Column names in the tables cannot contain the "-" character, so if you change it to "sample_id", that works for me. I'll be adding this information to the help text and the documentation.

Please let me know if that change and the fix I added solve the problem, or if you run into any other issues.

**Comment by Qepanna** [comment]
Thank you for your help! All problems solved. :)
